### ISSUE TITLE
UserDataChunks fails due to namespaced typeName

### ISSUE THREAD

**Issue by bgk-** [BanchouBoo/tatl#2]
Received an error on zig version 0.10.0-dev.4198+5e0d8a435

```
 tatl.zig:439:43: error: no field named 'tatl.Layer' in union 'tatl.UserDataChunks'
        return @unionInit(UserDataChunks, name, pointer);
```

I'm just learning Zig so I'm not sure if there's a better way, but I've resolved it by slicing the value of @typeName. Though I'm unsure if namespaces are created from the filename or the build addAsPackage name. So, if it's possible that another project has the namespace changed from "tatl" to something else, this fix could fail.

```
438  -         const name = @typeName(@typeInfo(@TypeOf(pointer)).Pointer.child);
438 +        const name = @typeName(@typeInfo(@TypeOf(pointer)).Pointer.child)[5..];
```

**Comment by BanchouBoo** [comment]
Off the top of my head, `std.mem.splitBackwards` should be a good solution in all contexts, but I'll ask around first to see if there's a more intuitive way to get the type name without the namespace.

**Comment by BanchouBoo** [comment]
Fixed using the aforementioned method.
